# Generated by Django 3.2.17 on 2023-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230210_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
