# Generated by Django 3.2.17 on 2023-02-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
