# Generated by Django 3.2.12 on 2023-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
