# Generated by Django 3.2.12 on 2023-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20230211_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
